# Update skill.json at neon_skills repository
name: Update html and README.md
on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - master

jobs:
  update_skill_docs:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Script Dependencies
        run: |
          python -m pip install tabulate requests
      - name: Update Files
        run: python scripts/parse_skill_data.py
      # TODO: Push updates, PR New Additions
      - name: Push File Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update html and README.md